#! /bin/sh

sxhkd &
xrandr --output eDP --off
bspc monitor -d 1 2 3 4 5
bspc monitor -g 1920x1080+0+0

#wallpaper
nitrogen --restore &&

#compositor
compton --backend glx &

#polybar
$HOME/.config/polybar/launch.sh

#network-manager-applet
nm-applet &

#pywal
#wal -R

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# restart window titles daemon
#while pgrep -u $UID -f bspwm_window_titles >/dev/null; do pkill -f bspwm_window_titles; done
#bspwm_window_titles &
